name: Build and upload artifact

on:
  push:
    branches: [ RaylibPort ]
  pull_request:
    branches: [ RaylibPort ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: 'RaylibPort'
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1
    - name: Build
      run: ./build_all.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Output
        path: zig-out/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: zig-out/emcc/CrossyRoady

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

